definitions:
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  model.Flight:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      endTime:
        type: string
      id:
        type: string
      lat:
        type: number
      lng:
        type: number
      robotId:
        type: string
      startTime:
        type: string
      updatedAt:
        type: string
    type: object
  model.Robot:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      generation:
        type: integer
      id:
        type: string
      name:
        type: string
      updatedAt:
        type: string
    type: object
info:
  contact: {}
  version: 1.0.0
  title: Drone Flight Log API  
paths:
  /api/robot:
    post:
      consumes:
      - application/json
      description: Create a robot
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Robot'
      tags:
      - Robot
  /api/robots:
    get:
      consumes:
      - application/json
      description: Get multiple robots
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Robot'
            type: array
      tags:
      - Robot
  /api/v1/flight:
    post:
      consumes:
      - application/json
      description: Create a flight
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Flight'
      tags:
      - Flights
  /api/v1/flight/{id}:
    get:
      consumes:
      - application/json
      description: Get one flight by ID
      produces:
      - application/json
      parameters:
        - name: id
          in: path
          description: UUID of flight to fetch
          required: true
          type: string
          format: string      
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Flight'
      tags:
      - Flight
  /api/v1/flights:
    get:
      consumes:
      - application/json
      description: Get all existing flights
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Flight'
            type: array
      tags:
      - Flights
  /api/v1/flights/csv:
    post:
      consumes:
      - text/csv
      description: Create a flight
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Flight'
      tags:
      - Flights
  /api/v1/robot/{id}:
    get:
      consumes:
      - application/json
      description: Get one robot by ID
      produces:
      - application/json
      parameters:
        - name: id
          in: path
          description: UUID of robot to fetch
          required: true
          type: string
          format: string      
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Flight'
      tags:
      - Flight
swagger: "2.0"
