name: CI - Build & Test
on:
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_test_golang:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Login to Github Repository to pull cache
      run: echo ${GITHUB_TOKEN} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin

    - name: Run unit tests baremetal
      run: |
        make test
